# coding: utf-8

"""
    clair.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import clairclient
from clairclient.api.ancestry_service_api import AncestryServiceApi  # noqa: E501
from clairclient.rest import ApiException


class TestAncestryServiceApi(unittest.TestCase):
    """AncestryServiceApi unit test stubs"""

    def setUp(self):
        self.api = clairclient.api.ancestry_service_api.AncestryServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_ancestry(self):
        """Test case for get_ancestry

        """
        pass

    def test_post_ancestry(self):
        """Test case for post_ancestry

        """
        pass


if __name__ == '__main__':
    unittest.main()
