# coding: utf-8

"""
    clair.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import clairclient
from clairclient.models.clairpb_layer import ClairpbLayer  # noqa: E501
from clairclient.rest import ApiException


class TestClairpbLayer(unittest.TestCase):
    """ClairpbLayer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClairpbLayer(self):
        """Test ClairpbLayer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clairclient.models.clairpb_layer.ClairpbLayer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
