# coding: utf-8

"""
    clair.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import clairclient
from clairclient.api.notification_service_api import NotificationServiceApi  # noqa: E501
from clairclient.rest import ApiException


class TestNotificationServiceApi(unittest.TestCase):
    """NotificationServiceApi unit test stubs"""

    def setUp(self):
        self.api = clairclient.api.notification_service_api.NotificationServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_notification(self):
        """Test case for get_notification

        """
        pass

    def test_mark_notification_as_read(self):
        """Test case for mark_notification_as_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
