# coding: utf-8

"""
    clair.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import clairclient
from clairclient.models.protobuf_empty import ProtobufEmpty  # noqa: E501
from clairclient.rest import ApiException


class TestProtobufEmpty(unittest.TestCase):
    """ProtobufEmpty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProtobufEmpty(self):
        """Test ProtobufEmpty"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clairclient.models.protobuf_empty.ProtobufEmpty()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
