# coding: utf-8

"""
    clair.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 3.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ClairpbGetAncestryResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'ancestry': 'ClairpbAncestry',
        'status': 'ClairpbClairStatus'
    }

    attribute_map = {
        'ancestry': 'ancestry',
        'status': 'status'
    }

    def __init__(self, ancestry=None, status=None):  # noqa: E501
        """ClairpbGetAncestryResponse - a model defined in OpenAPI"""  # noqa: E501

        self._ancestry = None
        self._status = None
        self.discriminator = None

        if ancestry is not None:
            self.ancestry = ancestry
        if status is not None:
            self.status = status

    @property
    def ancestry(self):
        """Gets the ancestry of this ClairpbGetAncestryResponse.  # noqa: E501


        :return: The ancestry of this ClairpbGetAncestryResponse.  # noqa: E501
        :rtype: ClairpbAncestry
        """
        return self._ancestry

    @ancestry.setter
    def ancestry(self, ancestry):
        """Sets the ancestry of this ClairpbGetAncestryResponse.


        :param ancestry: The ancestry of this ClairpbGetAncestryResponse.  # noqa: E501
        :type: ClairpbAncestry
        """

        self._ancestry = ancestry

    @property
    def status(self):
        """Gets the status of this ClairpbGetAncestryResponse.  # noqa: E501


        :return: The status of this ClairpbGetAncestryResponse.  # noqa: E501
        :rtype: ClairpbClairStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ClairpbGetAncestryResponse.


        :param status: The status of this ClairpbGetAncestryResponse.  # noqa: E501
        :type: ClairpbClairStatus
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClairpbGetAncestryResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
