# coding: utf-8

"""
    clair.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 3.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class PostAncestryRequestPostLayer(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'hash': 'str',
        'path': 'str',
        'headers': 'dict(str, str)'
    }

    attribute_map = {
        'hash': 'hash',
        'path': 'path',
        'headers': 'headers'
    }

    def __init__(self, hash=None, path=None, headers=None):  # noqa: E501
        """PostAncestryRequestPostLayer - a model defined in OpenAPI"""  # noqa: E501

        self._hash = None
        self._path = None
        self._headers = None
        self.discriminator = None

        if hash is not None:
            self.hash = hash
        if path is not None:
            self.path = path
        if headers is not None:
            self.headers = headers

    @property
    def hash(self):
        """Gets the hash of this PostAncestryRequestPostLayer.  # noqa: E501


        :return: The hash of this PostAncestryRequestPostLayer.  # noqa: E501
        :rtype: str
        """
        return self._hash

    @hash.setter
    def hash(self, hash):
        """Sets the hash of this PostAncestryRequestPostLayer.


        :param hash: The hash of this PostAncestryRequestPostLayer.  # noqa: E501
        :type: str
        """

        self._hash = hash

    @property
    def path(self):
        """Gets the path of this PostAncestryRequestPostLayer.  # noqa: E501


        :return: The path of this PostAncestryRequestPostLayer.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this PostAncestryRequestPostLayer.


        :param path: The path of this PostAncestryRequestPostLayer.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def headers(self):
        """Gets the headers of this PostAncestryRequestPostLayer.  # noqa: E501


        :return: The headers of this PostAncestryRequestPostLayer.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._headers

    @headers.setter
    def headers(self, headers):
        """Sets the headers of this PostAncestryRequestPostLayer.


        :param headers: The headers of this PostAncestryRequestPostLayer.  # noqa: E501
        :type: dict(str, str)
        """

        self._headers = headers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PostAncestryRequestPostLayer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
